export const RESET_ALL_DATA = 'RESET_ALL_DATA';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const GET_TODO_DATA_REQUEST = 'GET_TODO_DATA_REQUEST';
export const GET_TODO_DATA_SUCCESS = 'GET_TODO_DATA_SUCCESS';
export const GET_TODO_DATA_FAILED = 'GET_TODO_DATA_FAILED';

export const GET_POSTS_DATA_REQUEST = 'GET_POSTS_DATA_REQUEST';
export const GET_POSTS_DATA_SUCCESS = 'GET_POSTS_DATA_SUCCESS';
export const GET_POSTS_DATA_FAILED = 'GET_POSTS_DATA_FAILED';
